-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), UI.GENDER

# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_INFO.GENDER, COUNT( DISTINCT ONLINE_SALE.USER_ID) AS USERS
# FROM ONLINE_SALE
# JOIN USER_INFO
# ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID AND
# GENDER IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER 
# ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER