-- 코드를 입력하세요
SELECT CAR_ID, PLAN.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM (
SELECT HISTORY_ID, RH.CAR_ID, CAR_TYPE, DAILY_FEE, MAX(SUB_AVAILABILITY) AS AVAILABILITY
FROM 
(SELECT HISTORY_ID, CAR_ID,
CASE WHEN (START_DATE <= '2022-11-01' AND END_DATE <= '2022-11-01') OR (START_DATE > '2022-11-30' AND END_DATE > '2022-11-30') THEN '대여 가능' 
ELSE '대여 중' END AS SUB_AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS RC ON RC.CAR_ID = RH.CAR_ID
WHERE (RC.CAR_TYPE = "SUV" OR RC.CAR_TYPE = "세단")
GROUP BY RH.CAR_ID
) AS INFO
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON INFO.CAR_TYPE = PLAN.CAR_TYPE AND DURATION_TYPE = "30일 이상"
WHERE AVAILABILITY = "대여 가능" AND (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) >= 500000 AND (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)  < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC