-- 코드를 입력하세요
SELECT C1.CART_ID
FROM CART_PRODUCTS AS C1
JOIN CART_PRODUCTS AS C2 ON C1.CART_ID = C2.CART_ID
WHERE (C1.NAME LIKE "Milk" AND C2.NAME LIKE "Yogurt") OR
(C2.NAME LIKE "Milk" AND C1.NAME LIKE "Yogurt")
GROUP BY C1.CART_ID
ORDER BY C1.ID