-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE AS ONL
# WHERE DATE_FORMAT(ONL.SALES_DATE, "%Y-%m") = "2022-03"
# UNION ALL
# SELECT PRODUCT_ID, NULL, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE
# FROM OFFLINE_SALE AS OFF
# WHERE DATE_FORMAT(OFF.SALES_DATE, "%Y-%m") = "2022-03"
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
WHERE MONTH(SALES_DATE)=3 
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),PRODUCT_ID,NULL,SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE MONTH(SALES_DATE)=3 
ORDER BY 1,2,3
