-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PUCRHASED_USERS,
ROUND( COUNT(DISTINCT UI.USER_ID) * 1.0 / (
SELECT COUNT(DISTINCT USER_ID)
FROM USER_INFO
WHERE YEAR(JOINED) = "2021")
, 1) AS PURCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
WHERE YEAR(JOINED) = "2021"
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH