-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-08" AND DATE_FORMAT(START_DATE, "%Y-%m") <= "2022-10"
GROUP BY CAR_ID
HAVING COUNT(*) >= 5
) and start_date between '2022-08-01' and '2022-10-31'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH, CAR_ID DESC