# SELECT * ch.car_id AS CAR_ID, ch.car_type AS CAR_TYPE, ROUND(ch.daily_fee * 30 * (100 - p.discount_rate) / 100) AS FEE
# FROM 
# (SELECT c.car_id, c.car_type, c.daily_fee
# FROM CAR_RENTAL_COMPANY_CAR AS c
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h ON c.car_id = h.car_id
# WHERE (c.car_type = "세단" OR c.car_type = "SUV") AND (h.start_date <= "2022-11-01") AND (h.end_date >= "2022-11-30")) AS ch
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p ON ch.car_type = p.car_type
# WHERE (p.duration_type = "30일 이상") AND ((ch.daily_fee * 30 * (100 - p.discount_rate) / 100 >= 500000) AND (ch.daily_fee * 30 * (100 - p.discount_rate) / 100 < 2000000))
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;




# SELECT * # c.car_id, c.car_type, c.daily_fee
# FROM CAR_RENTAL_COMPANY_CAR AS c
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h ON c.car_id = h.car_id
# WHERE (c.car_type = "세단" OR c.car_type = "SUV") AND (h.start_date <= "2022-11-01") AND (h.end_date >= "2022-11-30")


SELECT CAR_ID, PLAN.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM (
SELECT HISTORY_ID, RH.CAR_ID, CAR_TYPE, DAILY_FEE, MAX(SUB_AVAILABILITY) AS AVAILABILITY
FROM 
(SELECT HISTORY_ID, CAR_ID,
CASE WHEN (START_DATE <= '2022-11-01' AND END_DATE <= '2022-11-01') OR (START_DATE > '2022-11-30' AND END_DATE > '2022-11-30') THEN '대여 가능' 
ELSE '대여 중' END AS SUB_AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS RC ON RC.CAR_ID = RH.CAR_ID
WHERE (RC.CAR_TYPE = "SUV" OR RC.CAR_TYPE = "세단")
GROUP BY RH.CAR_ID
) AS INFO
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON INFO.CAR_TYPE = PLAN.CAR_TYPE AND DURATION_TYPE = "30일 이상"
WHERE AVAILABILITY = "대여 가능" AND (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) >= 500000 AND (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)  < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC