-- 코드를 입력하세요
SELECT WRITER_ID AS USER_ID,
(SELECT NICKNAME FROM USED_GOODS_USER WHERE USER_ID = WRITER_ID) AS NICKNAME,
SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = "DONE" 
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)