-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (SELECT * FROM FOOD_PRODUCT ORDER BY PRICE DESC LIMIT 10000000000000000000) AS FOOD_PRODUCT
WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
GROUP BY CATEGORY
ORDER BY PRICE DESC