-- 코드를 입력하세요
SELECT HISTORY_ID,
CASE
WHEN CI.DURATION_TYPE IS NULL THEN FLOOR(DAILY_FEE * DD)
ELSE FLOOR(DAILY_FEE * DD * (100 - DISCOUNT_RATE) / 100)
END AS FEE
FROM (
SELECT C.CAR_TYPE, DAILY_FEE, HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DD,
CASE 
WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN "90일 이상"
WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN "30일 이상"
WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN "7일 이상"
ELSE NULL
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH ON C.CAR_ID = RH.CAR_ID
) AS CI
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP ON CI.DURATION_TYPE = DP.DURATION_TYPE AND CI.CAR_TYPE = DP.CAR_TYPE
WHERE CI.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC